import turtle as t

length = int(input())
length2 = int(input())
length3 = int(input())
def square(length):
    t.fd(length)
    t.left(90)
    t.fd(length)
    t.left(90)
    t.fd(length)
    t.left(90)
    t.fd(length)
    t.left(90)
def square2(length2):
    t.fd(length2)
    t.left(90)
    t.fd(length2)
    t.left(90)
    t.fd(length2)
    t.left(90)
    t.fd(length2)
    t.left(90)
def square3(length3):
    t.fd(length3)
    t.left(90)
    t.fd(length3)
    t.left(90)
    t.fd(length3)
    t.left(90)
    t.fd(length3)
    t.left(90)
    t.exitonclick()
square(length)
square2(length2)
square3(length3)